### ISSUE TITLE
404 error on click (Permalink to this timesheet)

### ISSUE THREAD

**Issue by tuxinaut** [nicStuff/redmine_timesheet_extensions#12]
Hello!

i create a custom time sheet! Then i click on (Permalink to this timesheet) and gets a 404 error!

Running
- Redmine 1.1.1 stable
- Rails 2.3.5
- Apache
- Phusion Passenger
- Using Firefox 4
- Ubuntu 10.10

<pre><code>
Processing ApplicationController#index (for 172.19.0.208 at 2011-04-11 15:29:41) [GET]
  Parameters: {"timesheet"=>{"total_hours"=>"0", "date_to"=>"2011-04-11", "projects"=>["4"], "date_from"=>"2011-03-12", "total_billed_hours"=>"0", "activities"=>["12"], "users"=>["1"], "sort"=>"issue_id", "selected_fields"=>{"billed_hours"=>"1", "comments"=>"1", "issue_id"=>"1", "project_id"=>"1", "activity_id"=>"1", "id"=>"1", "spent_on"=>"1", "user_id"=>"1", "hours"=>"1", "tweek"=>"1"}}}

ActionController::RoutingError (No route matches "/timesheet/report" with {:method=>:get}):
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:213:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

Rendering /srv/www/redmine.cevo.de/public/404.html (404 Not Found)
</code></pre>

I hope we can find a solution to this problem.

Thanks!

**Comment by nicStuff** [comment]
Thanks for the report, I will fix it as soon as possible.

Cheers

Nic

**Comment by nicStuff** [comment]
Fixed :).

nic

**Comment by tuxinaut** [comment]
That was very fast :) Lot of thanks!
