### ISSUE TITLE
NetworkError: 404 Not Found

### ISSUE THREAD

**Issue by tuxinaut** [nicStuff/redmine_timesheet_extensions#13]
Hello!

i create a custom time sheet! Then i  make a **right click** on a time entry an gets following error (in Firebug console)!

Running
- Redmine 1.1.1 stable
- Rails 2.3.5
- Apache
- Phusion Passenger
- Using Firefox 4
- Ubuntu 10.10

Firebug output

"NetworkError: 404 Not Found - http://172.19.0.XXX/timesheet/context_menu?authenticity_token=3ZFFu3tXMMdVezB4IAtRJ7430Bf5Lt7qQL4bY8rNOXX%3D&authenticity_token=3ZFFu3tXMMdVezB4IAtRJ7430Bf5Lt7qQL4bY8rNO6E%XX&timesheet%5Byear%5D=2011&timesheet%5Bmonth%5D=&timesheet%5Bperiod%5D=all&timesheet%5Bperiod_type%5D=2&timesheet%5Bdate_from%5D=2011-01-01%2000%3A00%3A00&timesheet%5Bdate_to%5D=2011-12-31%2023%3A59%3A59&timesheet%5Bsort%5D=comments&timesheet%5Bprojects%5D%5B%5D=4&timesheet%5Bactivities%5D%5B%5D=9&timesheet%5Bactivities%5D%5B%5D=12&timesheet%5Bactivities%5D%5B%5D=13&timesheet%5Bactivities%5D%5B%5D=14&timesheet%5Bactivities%5D%5B%5D=15&timesheet%5Bactivities%5D%5B%5D=16&timesheet%5Busers%5D%5B%5D=1&timesheet%5Bselected_fields%5D%5Bid%5D=1&timesheet%5Bselected_fields%5D%5Bproject_id%5D=1&timesheet%5Bselected_fields%5D%5Buser_id%5D=1&timesheet%5Bselected_fields%5D%5Bissue_id%5D=1&timesheet%5Bselected_fields%5D%5Bcomments%5D=1&timesheet%5Bselected_fields%5D%5Bactivity_id%5D=1&timesheet%5Bselected_fields%5D%5Bspent_on%5D=1&timesheet%5Bselected_fields%5D%5Btweek%5D=1&timesheet%5Bselected_fields%5D%5Bhours%5D=1&timesheet%5Bselected_fields%5D%5Bbilled_hours%5D=1&commit=Anwenden&_method=delete&ids%5B%5D=95
- _method   **delete**
- authenticity_token    **3ZFFu3tXMMdVezB4IAtRJ7430Bf5Lt7qQL4bY8rNOXX=**
- authenticity_token    **3ZFFu3tXMMdVezB4IAtRJ7430Bf5Lt7qQL4bY8rNOXX=**
- commit    **Anwenden**
- ids[] **95**
- timesheet[activities][]   **9**
- timesheet[activities][]   **12**
- timesheet[activities][]   **13**
- timesheet[activities][]   **14**
- timesheet[activities][]   **15**
- timesheet[activities][]   **16**
- timesheet[date_from]  **2011-01-01 00:00:00**
- timesheet[date_to]    **2011-12-31 23:59:59**
- timesheet[month]  
- timesheet[period] **all**
- timesheet[period_type]    **2**
- timesheet[projects][] **4**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[selected_fields...  **1**
- timesheet[sort]   **comments**
- timesheet[users][]    **1**
- timesheet[year]   **2011**

I hope we can find a solution to this problem.

Thanks!

**Comment by nicStuff** [comment]
Right, it makes a call to the wrong service. I will fix it.

nic

**Comment by tuxinaut** [comment]
Thanks
