### ISSUE TITLE
Export to CSV yields 406 NotAcceptable Error

### ISSUE THREAD

**Issue by jwwicks** [nicStuff/redmine_timesheet_extensions#15]
Steps to reproduce
1. I have about 50 plus projects with issues and time entries
2. Access the Timesheet from the main menu
3. Generate a report for one person selecting multiple projects, at  least 20 or more
4. Click the export to CSV link

<pre>
Processing CustomTimesheetsController#report to csv (for 150.70.172.102 at 2011-04-14 15:07:22) [GET]
  Parameters: {"format"=>"csv", "action"=>"report", "timesheet"=>{"date_to"=>"2011-04-01", "projects"=>["14", "13", "11", "30", "29", "36", "47", "67", "27", "17", "51", "1", "49", "73", "12", "37", "35", "28", "66", "41", "22", "26", "52", "56", "4", "71", "48", "54", "55", "10", "57", "23", "21", "24", "25", "3", "9", "16", "15", "7", "40", "33", "58", "53", "44", "45", "72", "43", "42", "74", "39", "64", "50", ""], "date_from"=>"2011-03-01", "activities"=>["8", "9", "10", "11", "12"]}, "controller"=>"custom_timesheets"}
Filter chain halted as [:check_if_login_required] rendered_or_redirected.
Completed in 7ms (View: 0, DB: 2) | 406 Not Acceptable [http://dev.greatlittlebook.com/custom_timesheet/report?format=csv&timesheet%5Bactivities%5D%5B%5D=8&timesheet%5Bactivities%5D%5B%5D=9&timesheet%5Bactivities%5D%5B%5D=10&timesheet%5Bactivities%5D%5B%5D=11&timesheet%5Bactivities%5D%5B%5D=12&timesheet%5Bdate_from%5D=2011-03-01&timesheet%5Bdate_to%5D=2011-04-01&timesheet%5Bprojects%5D%5B%5D=14&timesheet%5Bprojects%5D%5B%5D=13&timesheet%5Bprojects%5D%5B%5D=11&timesheet%5Bprojects%5D%5B%5D=30&timesheet%5Bprojects%5D%5B%5D=29&timesheet%5Bprojects%5D%5B%5D=36&timesheet%5Bprojects%5D%5B%5D=47&timesheet%5Bprojects%5D%5B%5D=67&timesheet%5Bprojects%5D%5B%5D=27&timesheet%5Bprojects%5D%5B%5D=17&timesheet%5Bprojects%5D%5B%5D=51&timesheet%5Bprojects%5D%5B%5D=1&timesheet%5Bprojects%5D%5B%5D=49&timesheet%5Bprojects%5D%5B%5D=73&timesheet%5Bprojects%5D%5B%5D=12&timesheet%5Bprojects%5D%5B%5D=37&timesheet%5Bprojects%5D%5B%5D=35&timesheet%5Bprojects%5D%5B%5D=28&timesheet%5Bprojects%5D%5B%5D=66&timesheet%5Bprojects%5D%5B%5D=41&timesheet%5Bprojects%5D%5B%5D=22&timesheet%5Bprojects%5D%5B%5D=26&timesheet%5Bprojects%5D%5B%5D=52&timesheet%5Bprojects%5D%5B%5D=56&timesheet%5Bprojects%5D%5B%5D=4&timesheet%5Bprojects%5D%5B%5D=71&timesheet%5Bprojects%5D%5B%5D=48&timesheet%5Bprojects%5D%5B%5D=54&timesheet%5Bprojects%5D%5B%5D=55&timesheet%5Bprojects%5D%5B%5D=10&timesheet%5Bprojects%5D%5B%5D=57&timesheet%5Bprojects%5D%5B%5D=23&timesheet%5Bprojects%5D%5B%5D=21&timesheet%5Bprojects%5D%5B%5D=24&timesheet%5Bprojects%5D%5B%5D=25&timesheet%5Bprojects%5D%5B%5D=3&timesheet%5Bprojects%5D%5B%5D=9&timesheet%5Bprojects%5D%5B%5D=16&timesheet%5Bprojects%5D%5B%5D=15&timesheet%5Bprojects%5D%5B%5D=7&timesheet%5Bprojects%5D%5B%5D=40&timesheet%5Bprojects%5D%5B%5D=33&timesheet%5Bprojects%5D%5B%5D=58&timesheet%5Bprojects%5D%5B%5D=53&timesheet%5Bprojects%5D%5B%5D=44&timesheet%5Bprojects%5D%5B%5D=45&timesheet%5Bprojects%5D%5B%5D=72&timesheet%5Bprojects%5D%5B%5D=43&timesheet%5Bprojects%5D%5B%5D=42&timesheet%5Bprojects%5D%5B%5D=74&timesheet%5Bprojects%5D%5B%5D=39&timesheet%5Bprojects%5D%5B%5D=64&timesheet%5Bprojects%5D%5B%5D=50&timesheet%5Bprojects%5D%5B%5D=]
</pre>

Works with about 15 projects but might be too long a URL

Jw

**Comment by nicStuff** [comment]
Sincerely this is the first time that I see a real case of 406 error, and in the plugin... Too young :). I will look at this asap.

**Comment by tigaszzz** [comment]
Hi Nicola Is there any fix for this ? i'm getting 20.000 chars URLs also, while generating reports.

Cheers,
tigas

**Comment by nicStuff** [comment]
I observe that the URL in jwwicks post is composed by 2083 characters and ends with "=", so it seems that "something" cut the original request before sending it to the server.

According with the fact that [IE "cuts" the URL to 2083 characters](http://support.microsoft.com/kb/208427/en-us) I suppose that you used internet Explorer, so this is a limitation of IE. I put a 20000 characters long URL in firefox and it worked fine.

I consider this issue closed since it can be avoided "simply" using another browser, e.g. firefox. If a lot of people really needs to work with IE I will solve this issue, but only if really necessary.
