### ISSUE TITLE
Issue update with time entry : get error 500

### ISSUE THREAD

**Issue by csanquer** [nicStuff/redmine_timesheet_extensions#2]
Hi,

I' ve found a new problem. Sometimes when i submit a issue update with a filled time entry, i get a 500 error page.

Related log : 

```
ActionView::TemplateError (undefined method `[]' for nil:NilClass) on line # 22 of vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:
19:
20: <h2><%= l(:label_spent_time) %></h2>
21:
22: <% labelled_tabular_form_for :time_entry, @time_entry, :url => {:action => 'edit', :id => @time_entry, :project_id => @time_entry.project} do |f| %>
23:   <%= error_messages_for 'time_entry' %>
24:   <%= back_url_hidden_field_tag %>
25: 

    app/helpers/application_helper.rb:702:in `labelled_tabular_form_for'
    vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:22:in `_run_rhtml_vendor47plugins47redmine_timesheet_extensions47app47views47timelog47edit46rhtml'

Rendering /home/redmine/redmine-www/public/500.html (500 Internal Server Error)
```

**Comment by nicStuff** [comment]
Good report, thank you: I will look at the problem in these days. Cheers

nicola

**Comment by did1979** [comment]
Hello, I have the same issue : I've tried to edit or add a new entrie in a demand and in the log I got :

Processing TimelogController#edit (for 192.168.168.159 at 2011-01-06 12:30:58) [GET]
  Parameters: {"issue_id"=>"12", "action"=>"edit", "controller"=>"timelog"}

ActiveRecord::MissingAttributeError (missing attribute: hours):
  app/models/time_entry.rb:47:in `after_initialize'
  app/controllers/timelog_controller.rb:168:in`new'
  app/controllers/timelog_controller.rb:168:in `edit'

Rendering /home/redmine/redmine/public/500.html (500 Internal Server Error)

Sometimes, when I refresh the pasge it works, but it is hasardous.

thanks.
did

**Comment by nicStuff** [comment]
Hello csanquer, I tried to reproduce the bug but I was blocked by the problem described in the issue 4. So I resolved that issue, then I tried to reproduce the bug many times without success (i.e. I never saw the problem you described). Perhaps now the bug you reported is resolved, give it a try if you want with the updated version of the plugin.

Dear did1979, unfortunately I wasn't able to reproduce your problem too.

Anyway, if you like you can provide some more information about the context where the bugs happened (e.g. ruby version, redmine version, rails version, operating system).

Bye!

**Comment by cod3master** [comment]
Hello, I have the same error.
The error only occurs when i go to the TimeSheet Report, after that view the system has errors in the time entry view. I can enter as many time-entries as I want, without errors, but when I go to the TimeSheet Report it doesn't work anymore
Then I need to restart redmine (apache/mysql etc.) and the problem is gone.

I hope this helps reproducing the steps. 
Thanks

**Comment by cod3master** [comment]
I also found this in the logs

Processing TimelogController#edit (for 10.0.0.12 at 2011-01-16 17:29:21) [GET]
  Parameters: {"issue_id"=>"26", "action"=>"edit", "controller"=>"timelog"}

ActiveRecord::MissingAttributeError (missing attribute: hours):
  app/models/time_entry.rb:47:in `after_initialize'
  app/controllers/timelog_controller.rb:168:in`new'
  app/controllers/timelog_controller.rb:168:in `edit'

**Comment by cod3master** [comment]
btw.try this open a new time entry and open in a new window the custom_timesheet_controller view, then switch back and refresh the time entry window. voila.

**Comment by did1979** [comment]
I think this issue can be caused by the entries saved before inslatting the module timesheet.
In the standard Issue form we have not the hours box.
I don't know if it is possible but maybe you should disable the form box in the standard modification form to avoid the 2 different ways to fill time entries. 

thanks.

**Comment by cod3master** [comment]
I can't exactly understand what you mean. There are 2 ways of enter the time, on the Issue directly and/or by clicking on the "Log Time" icon. Log Time opens
"..../issues/45/time_entries/new", same like clicking on the "Edit Time" in your TimeSheet report which opens "..../issues/44/time_entries/edit". Both genererate the errors only _after_ calling the Report once. It seems that the Report modifies something which is used by both Modules. Do you modify the object? Maybe you should create a new instance on the Report.

**Comment by nicStuff** [comment]
Thank you guys for your effort, excuse me but at this moment I'm having some trouble: I will face the problems in the weekend with the information you provided. Thanks once more time

nic

**Comment by nicStuff** [comment]
Hello to you, in these days I made every step of every comment without reproducing the bug.
I'm seriously thinking that the bug happens in a specific version of redmine (or even rails, ruby. Anyway I'm using redmine 1.0.3.stable for developing, rails 2.3.5 and ruby 1.8.7 patchlevel 249): I will go more deep in the problem as soon as possible, with different versions of redmine.

After the problem happened did you try to erase the browser cache vel logout and see if the problem was still there?

Best regards!

nic

**Comment by cod3master** [comment]
Hi nic
I use redmin 1.0.4, ruby 1.8.7 patchlevel 249, rails 2.3.9.
I could reproduce it on a clean firefox profile (empty cookies, empty cache)

Kind Regards,
gt

**Comment by nicStuff** [comment]
Is the bug still there even in the plugin with the latest updates?

**Comment by cod3master** [comment]
Yes the problems are still there, same behaviour.

**Comment by fixwerx** [comment]
Nic,

I am running Redmine 1.1.2 on Enterprise ruby with passenger and apache. I can consistently reproduce the error on my Mac with Safari and Firefox browsers with the following steps:
1. Login and select a project.
2. Select an issue and 'log time'. This will work, and you can enter/edit time for any project/issue and not have an error. 
3. Now go to the Timesheet menu link. Set your filter preferences and 'apply' them to execute the report. 
4. Now go to an issue (or just try to edit a time entry from the report screen). You will get the error at this point.

I continue to get the error anytime I try to enter or edit time, from within an issue update or using a 'log time' link. 

If I sign off and wait several minutes (not sure exactly how long, but at least 10 minutes), I can the sign back in and time entry and edits work again. Once I run a report again the problem will occur until I log out for a while. 

I think this may be related to Redmine 1.1.x but I am not 100% sure on this. I also think it has something to do with the custom_timesheets_controller.rb and how it is using sessions. I have tried a few corrections but nothing has worked so far. 

I am posting entries from my log file for a good time entry followed by running a report followed by trying to log time again. The attempt at entering a new time entry after the report has the error. 

Processing IssuesController#show (for 10.58.1.27 at 2011-03-14 03:33:59) [GET]
  Parameters: {"action"=>"show", "id"=>"3", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml
Completed in 727ms (View: 601, DB: 22) | 200 OK [http://10.58.1.33/issues/3]

Processing TimelogController#new (for 10.58.1.27 at 2011-03-14 03:34:02) [GET]
  Parameters: {"issue_id"=>"3", "action"=>"new", "controller"=>"timelog"}
Rendering template within layouts/base
Rendering timelog/edit
Completed in 176ms (View: 129, DB: 6) | 200 OK [http://10.58.1.33/issues/3/time_entries/new]

Processing TimelogController#create (for 10.58.1.27 at 2011-03-14 03:34:32) [POST]
  Parameters: {"time_entry"=>{"billed_hours"=>"2", "comments"=>"Test Time Entry", "issue_id"=>"3", "end_minute"=>"15", "activity_id"=>"8", "start_hour"=>"7", "spent_on"=>"2011-03-13", "start_minute"=>"15", "hours"=>"2", "end_hour"=>"9"}, "back_url"=>"http%3A%2F%2F10.58.1.33%2Fissues%2F3", "commit"=>"Save", "project_id"=>"test", "action"=>"create", "authenticity_token"=>"wzAUmVMQ1KydWElPGhHUKzC4wv6Hk78D0XE/aRpOLNg=", "controller"=>"timelog"}
Start & end time: 435 555
Data start: Sun Mar 13 07:15:00 UTC 2011
Redirected to http://10.58.1.33/issues/3
Completed in 107ms (DB: 59) | 302 Found [http://10.58.1.33/projects/test/timelog/create]

Processing IssuesController#show (for 10.58.1.27 at 2011-03-14 03:34:32) [GET]
  Parameters: {"action"=>"show", "id"=>"3", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml
Completed in 434ms (View: 352, DB: 9) | 200 OK [http://10.58.1.33/issues/3]

Processing CustomTimesheetsController#index (for 10.58.1.27 at 2011-03-14 03:34:38) [GET]
  Parameters: {"action"=>"index", "controller"=>"custom_timesheets"}
Rendering template within layouts/base
Rendering custom_timesheets/index
Completed in 125ms (View: 88, DB: 2) | 200 OK [http://10.58.1.33/custom_timesheet_controller]

Processing CustomTimesheetsController#report (for 10.58.1.27 at 2011-03-14 03:34:48) [POST]
  Parameters: {"commit"=>"Apply", "action"=>"report", "authenticity_token"=>"wzAUmVMQ1KydWElPGhHUKzC4wv6Hk78D0XE/aRpOLNg=", "timesheet"=>{"month"=>"", "date_to"=>"2011-03-14", "period"=>"all", "projects"=>["4", "5"], "date_from"=>"2011-03-11", "activities"=>["8", "9"], "period_type"=>"2", "year"=>"2011", "users"=>["1"], "sort"=>"comments", "selected_fields"=>{"billed_hours"=>"1", "comments"=>"1", "project_id"=>"1", "issue_id"=>"1", "activity_id"=>"1", "id"=>"1", "spent_on"=>"1", "user_id"=>"1", "hours"=>"1", "tweek"=>"1"}}, "controller"=>"custom_timesheets"}
Rendering template within layouts/base
Rendering custom_timesheets/report
Completed in 734ms (View: 667, DB: 9) | 200 OK [http://10.58.1.33/custom_timesheet/report]

Processing ProjectsController#index (for 10.58.1.27 at 2011-03-14 03:34:53) [GET]
  Parameters: {"action"=>"index", "controller"=>"projects"}
Rendering template within layouts/base
Rendering projects/index
Completed in 66ms (View: 53, DB: 2) | 200 OK [http://10.58.1.33/projects]

Processing ProjectsController#show (for 10.58.1.27 at 2011-03-14 03:34:55) [GET]
  Parameters: {"action"=>"show", "id"=>"test", "controller"=>"projects"}
Rendering template within layouts/base
Rendering projects/show
Completed in 161ms (View: 100, DB: 10) | 200 OK [http://10.58.1.33/projects/test]

Processing IssuesController#index (for 10.58.1.27 at 2011-03-14 03:34:57) [GET]
  Parameters: {"project_id"=>"test", "set_filter"=>"1", "action"=>"index", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/index.rhtml
Completed in 334ms (View: 234, DB: 10) | 200 OK [http://10.58.1.33/projects/test/issues?set_filter=1]

Processing IssuesController#show (for 10.58.1.27 at 2011-03-14 03:34:58) [GET]
  Parameters: {"action"=>"show", "id"=>"3", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml
Completed in 737ms (View: 656, DB: 9) | 200 OK [http://10.58.1.33/issues/3]

Processing TimelogController#new (for 10.58.1.27 at 2011-03-14 03:35:02) [GET]
  Parameters: {"issue_id"=>"3", "action"=>"new", "controller"=>"timelog"}

ActiveRecord::MissingAttributeError (missing attribute: hours):
  app/models/time_entry.rb:47:in `after_initialize'
  app/controllers/timelog_controller.rb:109:in`new'
  app/controllers/timelog_controller.rb:109:in `new'
  passenger (2.2.14) lib/phusion_passenger/rack/request_handler.rb:92:in`process_request'
  passenger (2.2.14) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:441:in`start_request_handler'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/utils.rb:252:in`safe_fork'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in`**send**'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:163:in `start'
  passenger (2.2.14) lib/phusion_passenger/railz/application_spawner.rb:222:in`start'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  passenger (2.2.14) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  passenger (2.2.14) lib/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
  passenger (2.2.14) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

Rendering /var/www/railsapp/public/500.html (500 Internal Server Error)

mark

**Comment by fixwerx** [comment]
Nic,

I forgot to give a couple of more details in my previous post.
I am using Rails 2.3.5

I have tried clearing my browser's cache and clearing all cookies before signing in and that did not help. In all cases I have to wait for a while then sign back in and the problem is resolved. 

Mark

**Comment by nicStuff** [comment]
Thank you for the splendin trace Mark: following your steps one by one the bug didn't appear to me, with different redmine versions. I think like you that it's a sessions related problem, this is the reason for which I asked if it works after a cache clear..

At this point I think that I'll have to do debugging with the collaboration of all you (onbviously only who wants) in this manner: I will apply a possible correction, commit it in a branch named '500-fix'. Then you check out and tell me what happens...

By the way, what version of firefox are you using? Did you try with other browsers (e.g. chrome, opera)? What ruby interpreter are you using (MRI, the native interpreter, JRuby..)?

Anyway, a dirty and limited fix which isn't always applicable is to restart the server..

See you soon

nic

**Comment by nicStuff** [comment]
Well, I found some time to test everything **in a production environment** with apache and passenger and **I was able to reproduce the problem**. All my previous tests were made with the server webrick.

I apologize to you for the inconvenient and for the spent time, I will try to understand the cause soon.

**Comment by nontster** [comment]
Hi, 

it might be Rails bug, please take a look at link below

https://rails.lighthouseapp.com/projects/8994/tickets/3165-activerecordmissingattributeerror-after-update-to-rails-v-234

http://blog.edseek.com/archives/2009/04/16/missingattributeerror-from-within-after_initialize/

I can reproduce this error by 
1. select Timesheet from top menu,
2. make a query by press Apply
3. select an issue and press Log time

after patch after_initialize method, I found another error instead.

app/models/time_entry.rb

<pre>
  def after_initialize
    if new_record? && self.activity.nil?
      if default_activity = TimeEntryActivity.default
        self.activity_id = default_activity.id
      end
     #self.hours = nil if self.hours == 0
      write_attribute(:hours, nil) if read_attribute(:hours) == 0
    end
  end
</pre>


log/production.log

<pre>
Processing TimelogController#new (for 10.196.111.183 at 2011-03-31 17:04:58) [GET]
  Parameters: {"issue_id"=>"66", "action"=>"new", "controller"=>"timelog"}
Rendering template within layouts/base
Rendering timelog/edit

ActionView::TemplateError (undefined method `[]' for nil:NilClass) on line #25 of vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:
22: <% labelled_tabular_form_for(:time_entry, @time_entry, :url => {
23:                                :action => (@time_entry.new_record? ? 'create' : 'update'),
24:                                :id => @time_entry,
25:                                :project_id => @time_entry.project
26:                              },
27:                              :html => {:method => @time_entry.new_record? ? :post : :put}) do |f| %>
28: 

    vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:25:in `_run_rhtml_vendor47plugins47redmine_timesheet_extensions47app47views47timelog47edit46rhtml'
    app/controllers/timelog_controller.rb:113:in `new'
    passenger (3.0.4) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
    passenger (3.0.4) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
    passenger (3.0.4) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
    passenger (3.0.4) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
    passenger (3.0.4) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
    passenger (3.0.4) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
    passenger (3.0.4) lib/phusion_passenger/utils.rb:479:in `safe_fork'
    passenger (3.0.4) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:180:in `start'
    passenger (3.0.4) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
    passenger (3.0.4) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
    passenger (3.0.4) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
    passenger (3.0.4) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
    passenger (3.0.4) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
    passenger (3.0.4) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    passenger (3.0.4) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
    passenger (3.0.4) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
    passenger (3.0.4) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.4) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.4) helper-scripts/passenger-spawn-server:99

Rendering /var/www/redmine/public/500.html (500 Internal Server Error)

</pre>


Is bug raised from custom_timesheet ?, this might not relate to Rails bug as I've mentioned above.

**Comment by jwwicks** [comment]
I confirm what fixwerks and nontster have reported.

Running- 
Redmine 1.1.2 stable
Rails 2.3.5
Apache
Phusion Passenger
Using Opera, IE, FF and Chrome
Windows 7

<pre>
Processing TimelogController#edit (for 67.169.226.245 at 2011-03-31 15:37:19) [GET]
  Parameters: {"action"=>"edit", "id"=>"679", "controller"=>"timelog"}
Rendering template within layouts/base
Rendering timelog/edit

ActionView::TemplateError (undefined method `[]' for nil:NilClass) on line #22 of vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:
19: 
20: <h2><%= l(:label_spent_time) %></h2>
21: 
22: <% labelled_tabular_form_for :time_entry, @time_entry, :url => {:action => 'edit', :id => @time_entry, :project_id => @time_entry.project} do |f| %>
23:   <%= error_messages_for 'time_entry' %>
24:   <%= back_url_hidden_field_tag %>
25: 

    app/helpers/application_helper.rb:756:in `labelled_tabular_form_for'
    vendor/plugins/redmine_timesheet_extensions/app/views/timelog/edit.rhtml:22:in `_run_rhtml_vendor47plugins47redmine_timesheet_extensions47app47views47timelog47edit46rhtml'
    /dh/passenger/lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
    /dh/passenger/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
    /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:400:in `start_request_handler'
    /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:351:in `handle_spawn_application'
    /dh/passenger/lib/phusion_passenger/utils.rb:184:in `safe_fork'
    /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:349:in `handle_spawn_application'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:163:in `start'
    /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:209:in `start'
    /dh/passenger/lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
    /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
    /dh/passenger/lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
    /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
    /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    /dh/passenger/lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
    /dh/passenger/lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
    /dh/passenger/lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'


Rendering /public/500.html (500 Internal Server Error)
</pre>

Jw

**Comment by nicStuff** [comment]
In this issue we were wrongly talking about 2 distinct problems which generate 500.

These 2 problems are the one reported in the first comment, which came with the issue opening and reported by csanquer, and the one reported in the issue 9. For being more clear, the "ActiveRecord::MissingAttributeError (missing attribute: hours)" bug isn't the topic of this issue while the "ActionView::TemplateError (undefined method `[]' for nil:NilClass)" is.

Beyond this conceptual distinction, I'm saying this to all you because **I posted a solution for the "ActiveRecord::MissingAttributeError"** in the "500-fix branch", which is treated in issue 9. Please let me know if it works.

nic

**Comment by nontster** [comment]
Hi Nic,

Problem solved, thank you so much. This is a great Redmine plug-in.

**Comment by nicStuff** [comment]
It seems that **the solution for "ActiveRecord::MissingAttributeError" solved the ActionView::TemplateError (undefined method `[]' for nil:NilClass) too** :).

Well, **I consider this bug closed too**, thank you for your contribution and your feedback.

Kind regards,

Nicola
