### ISSUE TITLE
Reset button on the timesheet filter form leads to 404

### ISSUE THREAD

**Issue by jasonsocha** [nicStuff/redmine_timesheet_extensions#3]
Handler for /timesheet/reset does not appear to exist?

**Comment by nicStuff** [comment]
Hi, yes I didn't set it up yet. I will add this functionality as soon as possible.
Thanks for the report

nicola

**Comment by nicStuff** [comment]
Corrected :). Cheers

nic

**Comment by jasonsocha** [comment]
Awesome, thanks for the fast update!
