### ISSUE TITLE
Cannot submit time from normal issue edit screen.

### ISSUE THREAD

**Issue by jasonsocha** [nicStuff/redmine_timesheet_extensions#4]
When filling in the normal "Spent Time" section of the issue update form, I get error

Start time can't be empty

But there is no Start time field on this page!

I would suggest that Start time and End time be optional.  Sometimes it is necessary to enter total hours without recording specific times.

Thanks!

**Comment by nicStuff** [comment]
Got it, this bug would require more time than the previous for beeing resolved, I hope to find the time to correct it in these two days.
In the meanwhile you can bypass the problem registering time after having updated the issue.
Another time, thanks for the report
bye!

nic

**Comment by nicStuff** [comment]
Should be fixed now. Please let me know if not! Cheers

nic

**Comment by jasonsocha** [comment]
Excellent!  I will test ASAP.
