### ISSUE TITLE
404 Page Not Found when entering time

### ISSUE THREAD

**Issue by bkuhns** [nicStuff/redmine_timesheet_extensions#5]
First I view an existing issue, then click the "log time" link. I enter the appropriate time entry with all the required fields. Then I click the submit button and I'm sent to a 404 error page. The URL being accessed is /projects/fakeproject/timelog/edit

**Comment by nicStuff** [comment]
Thanks for the report, I will check it soon

**Comment by allaire** [comment]
Any news on this?

**Comment by nicStuff** [comment]
"Sadly" for me everything works, perhaps it's related to redmine version or other underlying things.
First I will have to reproduce the bug, then I will be able to debug the plugin. bye-bye

nic

**Comment by clamor** [comment]
I got the same Error after I upgraded the installation from 1.0.4 to 1.1.0.

**Comment by csanquer** [comment]
i have this bug too in my redmine test environment :
redmine 1.1.0 
ruby 1.8.7
gem 1.4.1 
rails 2.3.5
rake 0.8.7

**Comment by did1979** [comment]
Hello,

I have the same issue with Redmine 1.1.1.stable.4802
gem 1.3.7
rake 0.8.7.
rails 2.3.5
ruby 1.8.7 (2008-08-11 patchlevel 72) [i486-linux]

Thanks,
did1979

**Comment by rhindes** [comment]
Hello, I have the same problem and found a fix (for redmine 1.1.x). The plugin overwrites /app/views/timelog/edit.rhtml. The form-action is assembled as follows: 

<pre>
&lt;% labelled_tabular_form_for :time_entry, @time_entry, :url => {:action => 'edit', :id => @time_entry, :project_id => @time_entry.project} do |f| %>
</pre>

Replace this line with the original and it works: 

<pre>
&lt;% labelled_tabular_form_for(:time_entry, @time_entry, :url => {
                               :action => (@time_entry.new_record? ? 'create' : 'update'),
                               :id => @time_entry,
                               :project_id => @time_entry.project
                             },
                             :html => {:method => @time_entry.new_record? ? :post : :put}) do |f| %>
</pre>

**Comment by clamor** [comment]
Thanks a lot, replacing with the original works here.

clamor

**Comment by ixti** [comment]
rhindes,

Thanks, man! Saved me lots of nerves! :))

**Comment by nicStuff** [comment]
Ok, it seems that the fix works for versions of redmine major or equal than 1.0.0 (looking at redmine source): so I won't simply add the fix to the source because it will generate other problems where the redmine version is less than 1.0.0.

As soon as possible, I will post the solution in a manner that it will be possible to download the right plugin given a redmine version.
I'm sorry for the lack of support, but I'm very very busy at home and at work.

Thank for your contribution, it's precious and it proves that the plugin seems useful.

nic

**Comment by nicStuff** [comment]
In the download section I've added a zip versione of the plugin which solves this problem (the solution is the one posted by rhindes).
The fix works for redmine 1.1.x as rhindes said and not for redmine 1.0.x as I said in the previous comment...

It would be precious if someone of you try this version and tell me if it works/doesn't work... Moreover, did you find the 500 bug (https://github.com/nicStuff/redmine_timesheet_extensions/issues#issue/2) too?

nic

**Comment by rhindes** [comment]
i get a different 500 sometimes:

log says:

<pre>
ActiveRecord::MissingAttributeError (missing attribute: hours):
  app/models/time_entry.rb:47:in `after_initialize'
</pre>


line 47 is:  

<pre>
self.hours = nil if hours == 0
</pre>


just out of curiosity i changed it to: 

<pre>
self.hours = nil if self.hours == 0
</pre>


and i watch the behaviour.
